apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deploy
  name: {{ .Values.deploymentnames.frontend }}
spec:
  replicas: {{ .Values.replicacount.frontend}}
  selector:
    matchLabels:
      app: frontend-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-deploy
    spec:
      containers:
      - image: {{ .Values.images.crmfrontend }}
        name: {{ .Values.containernames.frontend }}
        env: 
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SERVER_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SERVER_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SERVER_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SERVER_NAME           
        resources: {}
status: {}
