apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deploy
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.serviceName.frontend}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.ports.nodePortCrmFront}}
  selector:
    app: frontend-deploy
  type: NodePort
status:
  loadBalancer: {}
