apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deploy
  name: {{ .Values.deploymentNames.frontend }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: frontend-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-deploy
    spec:
      containers:
      - image: {{ .Values.images.crmfrontend }}
        name: {{ .Values.contconainerNames.frontend }}
        env: 
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configNames.secret}}
              key: DB_SERVER
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configNames.secret}}
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configNames.secret}}
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configNames.secret}}
              key: DB_NAME  
        resources: {}
status: {}
