apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-deploy
    app.kubernetes.io/managed-by: Helm
  name: svc-backend
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: backend-deploy
status:
  loadBalancer: {}
